### ISSUE TITLE
Need mempool payload type: union of tx, delegation payload and update payload

### ISSUE THREAD

**Issue by dcoutts** [input-output-hk/cardano-ledger-byron#514]
## Background

The mempool holds ledger objects that can be included into blocks. These same objects are  transmitted into or between mempools via the transaction submission protocol.

In Byron there are three kinds of ledger objects that can be included:
* transactions `ATxPayload`
* delegation certificates `Delegation.APayload`
* update system objects (proposals, votes) `Update.APayload`

(In Shelley this gets simplified down to just transactions, with all special things embedded withing transactions.)

## Proposed Solution

Add a new module with a new type and appropriate instances and helpers that is the sum of these three types.

It requires binary serialisation instances, but there are no backwards compatability concerns since it will be used with a new network protocol.

**Comment by edsko** [comment]
Relevant conversation with @ruhatch :

Edsko de Vries   [3 hours ago]
@ru just a question for when we do get to this -- remember how yestreday you told me there were two rules for transactions, one that verifies the witness and one that does not. are there similar rules for the other-things-that-are-in-blocks-but-are-not-technically-transactions? (I've called this `GenTx` in my code for now for "generalized transaction"... if you have a better name, do let me know :slightly_smiling_face: )

Ru Horlick   [1 hour ago]
Indeed there are:
- `Cardano.Chain.Delegation.Validation.Interface.updateDelegation` adds a list of certs to the delegation state
- `Cardano.Chain.Update.Validation.Interface.registerUpdate` applies the update payload to the update state

Edsko de Vries   [1 hour ago]
do they have two variants also?

Edsko de Vries   [1 hour ago]
one that checks signatures and one that doesn't?

Ru Horlick   [12 minutes ago]
No, because for them the signatures are further inside the payload, rather than wrapped on the outside

Ru Horlick   [12 minutes ago]
Might you need something like that?

Edsko de Vries   [3 minutes ago]
It's not an immediate priority, but eventually, yes. In the mempool when we re-assess which transactions are still valid after a block as been applied, we need to check things like "are there inputs still okay" (checkTx) but we can skip stuff like cryptographic signatures (checkTxWitness). The some goes for the other "generalized transactions"

Ru Horlick   [2 minutes ago]
Yeah, for those, we could probably add a `CheckSignatures` flag and ignore sig predicates if we've already done them

Edsko de Vries   [2 minutes ago]
that would be perfect.

Ru Horlick   [< 1 minute ago]
:+1:

**Comment by intricate** [comment]
~Forgive me if I'm misunderstanding, but would it make sense to just reuse the [`ABody`](https://github.com/input-output-hk/cardano-ledger/blob/master/cardano-ledger/src/Cardano/Chain/Block/Body.hs#L37) data type from `Cardano.Chain.Block.Body`? Just wondering since it seems to contain the relevant data we're looking for here.~

```
-- | 'Body' consists of payloads of all block components
data ABody a = ABody
  { bodyTxPayload     :: !(ATxPayload a)
  -- ^ UTxO payload
  , bodySscPayload    :: !SscPayload
  -- ^ Ssc payload
  , bodyDlgPayload    :: !(Delegation.APayload a)
  -- ^ Heavyweight delegation payload (no-ttl certificates)
  , bodyUpdatePayload :: !(Update.APayload a)
  -- ^ Additional update information for the update system
  } deriving (Eq, Show, Generic, Functor, NFData)
```

EDIT: @ruhatch just clarified this for me. I misunderstood the purpose of this.
