### ISSUE TITLE
Code for creating and signing transactions

### ISSUE THREAD

**Issue by ruhatch** [input-output-hk/cardano-ledger-byron#620]
## Background

We currently don't have any high-level functions to say, here are my transaction inputs, outputs, and keys, please make me a transaction.

## Proposed Solution

Write some high-level transaction creation functions - these will be needed by the wallet and can be reused in our elaboration code or other places.

**Comment by dcoutts** [comment]
We will need this for the node CLI, and probably need something like this for use in a customer-facing SDK.

@KtorZ will you need it for the wallet?

**Comment by KtorZ** [comment]
Will we rely on the node's command-line: likely not.
Will we offer the very same feature: likely yes. 

This belongs to this set of overlapping features that are somewhat useful to have in both command-lines IMO. Now, if we're all using Haskell and `optparse-applicative`, it'd be nice to do some level of code sharing, at least for the public-facing interface (using a language-neutral specification language for CLI like [docopt](http://docopt.org/) for instance). 

So far, in the Adrestia backlog, we've planned to design, document and expose a transaction builder / signer as an independent library and command-line. `cardano-wallet` would then include this in its own command-line. We can get some inspiration from what was done with `jcli` regarding transaction building. The CLI is quite practical to use (to some extend).

**Comment by dcoutts** [comment]
@KtorZ sorry, I wasn't clear enough.

Certainly the wallet will not use the node's CLI. The suggestion here is that the core code for tx construction live in the ledger library, along side the definition of the tx types etc. Then the wallet would import those types and tx construction functions, and add it's extra stuff on top. It would only be very low level tx construction: passing explicitly all the inputs, and for signing passing in the keys. So this allows layering the coin selection and the HD derivation etc on top.

**Comment by KtorZ** [comment]
@dcoutts building the transaction itself and signing it is not so much a problem if we have the binary serializers available, the rest is quite straightforward. 
One thing however that is particularly useful and that we are not necessarily looking to re-implement is the estimation of the transaction size based on a given coin selection (i.e., before the change addresses have been chosen). 
In Byron, this was slightly tricky because the choice of change address could change the size of the encoded end result and therefore, estimating a transaction could only be done with a certain error tolerance. I am not sure about the new address format you've opted for in Shelley, but being able to estimate the size of a transaction based on:

- A list of selected tx inputs
- A list of known tx outputs 
- A list of known outputs coins (i.e., outputs minus the address)

Would be very useful.

**Comment by kevinhammond** [comment]
This should now come under the Adrestia client library requirements, which we will raise in JIRA.
