### ISSUE TITLE
Test the new .API module

### ISSUE THREAD

**Issue by edsko** [input-output-hk/cardano-ledger-byron#707]
Although @redxaxder moved the consensus auxiliary glue layer around the Byron implementation to the new `.API` module in `cardano-ledger`, these new definitions are not yet incorporated in the _testing_ of the Byron ledger, which was the primary motivation for moving them in the first place: until these are tested, we cannot be sure that the Byron integration is correct.

**Comment by nfrisby** [comment]
Issue #715 is the kind of bug we hope this Issue will flush out.

**Comment by nc6** [comment]
We could test this with the following property:

A transaction tx should validate in the mempool in slot n iff a header-valid block containing only that transaction validates when issues in slot n

This should hopefully catch issues such as #715 (since the slot would have been incorrect and thus in some cases would not have validated in one place), whilst also enforcing a general relation between mempool operations and block validation.
