### ISSUE TITLE
Unclear Implementation of Genesis Key Delegation

### ISSUE THREAD

**Issue by troedfach** [input-output-hk/cardano-ledger-byron#721]
In Voting, in function registerVote [here](https://github.com/input-output-hk/cardano-ledger/blob/00d6cf3e82240f623863f4aec3aabb56f0c9ea5f/cardano-ledger/src/Cardano/Chain/Update/Validation/Voting.hs#L170), the voter is checked to ensure it is a delegate of a genesis key. However, valid voters include _both_ genesis keys and delegates (source: p.25 of formal ledger specification).

We noticed that the state in [here](https://github.com/input-output-hk/cardano-ledger/blob/98048d95823b72e409b07481761b8a59c892c56c/cardano-ledger/src/Cardano/Chain/Delegation/Validation/Interface.hs#L85) is initalised with genesis keys delegating to themselves, so genesis keys are always delegates, and as a result, the above check is valid for both genesis keys and delegates.

However, it seems quite unclear that genesis keys are delegates of themselves, and this doesn't seem to be reflected in the formal specification.

**Comment by dnadales** [comment]
Thanks for submitting this issue. 

I'm trying to understand what is the problem you're describing. We have that:

![image](https://user-images.githubusercontent.com/175315/74221923-78564c80-4cb3-11ea-8f89-c233f1cb0b1c.png)

and 

![image](https://user-images.githubusercontent.com/175315/74221954-8d32e000-4cb3-11ea-86aa-66a596bb0675.png)

So in principle the range of the delegation map can be the genesis keys.

There's also an initial rule that specifies that the allowed delegators delegate to themselves:

![image](https://user-images.githubusercontent.com/175315/74222036-c408f600-4cb3-11ea-88be-ad44147c5598.png)

And since:

![image](https://user-images.githubusercontent.com/175315/74222049-d2571200-4cb3-11ea-9eb0-2b59aed81251.png)


I thought it'd be clear that genesis keys are delegates of themselves initially.

**Comment by troedfach** [comment]
Thanks a lot for your reply.

My mistake, I missed the initial rule that specifies that the allowed delegators delegate to themselves. Everything is clear now.

**Comment by dnadales** [comment]
Great! Thanks a lot for auditing the specs and implementation, and keeping us sharp!
